feat: added json request body support in csharp
twilio/twilio-csharp pull request #686
Opened 2023-09-06 11:25 UTC by tiwarishubham635

# Fixes #

Added support for sending application/json(request body) in twilio-csharp

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-csharp/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

2023-09-08 06:22 UTC, sbansla requested changes

2023-09-08 06:22 UTC, sbansla commented on src/Twilio/Converters/DateTimeConverter.cs
> +using System;
We don't this.

2023-09-08 06:22 UTC, sbansla commented on src/Twilio/Rest/PreviewMessaging/Message.cs
> +using System;
This is autogenerated code by librarian. We don't need this. Same comment for MessageCreator.

2023-09-08 10:51 UTC, tiwarishubham635 reviewed
Removed unnecessary files

2023-09-09 13:26 UTC, sbansla approved these changes

2023-09-09 13:27 UTC, merged